project_id = "revgpspqpkjncosctnxo"

[auth.hook.send_email]
enabled = true
uri = "https://revgpspqpkjncosctnxo.supabase.co/functions/v1/auth-email-handler"

[functions.auth-email-handler]
verify_jwt = false

[functions.generate-photo-enhancement]
verify_jwt = true

[functions.manage-custom-model]
verify_jwt = true

[functions.delete-user-account]
verify_jwt = true

[functions.admin-actions]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false