project_id = "revgpspqpkjncosctnxo"

[functions.generate-photo-enhancement]
verify_jwt = true

[functions.manage-custom-model]
verify_jwt = true

[functions.delete-user-account]
verify_jwt = true

[functions.admin-actions]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false